# Generated by Django 4.2.1 on 2023-05-26 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
